source/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    IndexView
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home_page'),
    path('post/', include('personal_blog.urls.post_urls', namespace='posts')),
    path('author/', include('personal_blog.urls.author_urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_blog/models.py
from django.db import models
from .helpers.validators import at_least_3
from django.contrib.auth import get_user_model


class Author(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Author name')

    def __str__(self) -> str:
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Title')
    body = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Text', validators=(at_least_3,))
    author = models.ForeignKey(
        get_user_model(), 
        on_delete=models.SET_DEFAULT,
        default=1, 
        null=False, 
        related_name='posts',
        verbose_name='Author'
        )
    tags = models.ManyToManyField(
        'personal_blog.Tag',
        related_name='posts',
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation date and time')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Update date and time')

    def __str__(self):
        return f"#{self.pk} - {self.title}"
    
    class Meta:
        permissions = [
            ('can_read_post', 'Can read post')
        ]


class Comment(models.Model):
    text = models.TextField(max_length=1000, null=False, blank=False, verbose_name='Comment')
    author = models.ForeignKey(
        get_user_model(), 
        null=True, 
        blank=True, 
        on_delete=models.SET_DEFAULT,
        default=1, 
        related_name='comments',
        verbose_name='Author'
        )
    post = models.ForeignKey('personal_blog.Post', on_delete=models.CASCADE, related_name='comments',
                             verbose_name='Post')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation date and time')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Update date and time')

    def __str__(self) -> str:
        return self.text[:20]


class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='Tag')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation date and time')

    def __str__(self) -> str:
        return self.name

personal_blog/helpers/views.py
from django.views.generic import View, TemplateView
from django.shortcuts import get_object_or_404, render, redirect


class ParamMixin:
    form_class = None
    template_name = None
    redirect_url = ''
    model = None
    context_key = 'objects'
    key_kwarg = 'pk'

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url


class CustomFormView(View, ParamMixin):
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_valid(self, form):
        return redirect(self.get_redirect_url())
    
    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)
    
    def get_context_data(self, **kwargs):
        return kwargs
    

class CustomListView(TemplateView, ParamMixin):
    model = None
    context_key = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_objects()
        return context
    
    def get_objects(self):
        return self.model.objects.all()
    

class CustomDetailView(TemplateView, ParamMixin):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context


class CustomCreateView(View, ParamMixin):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())
    
    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)


class CustomUpdateView(View, ParamMixin):
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object)
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)
    
    def get_context_data(self, **kwargs):
        context = self.kwargs.copy()
        context[self.context_key] = self.object
        context.update(kwargs)
        return context
    
    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())
    
    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class CustomDeleteView(View, ParamMixin):
    confirm_deletion = True

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        self.perform_deletion()
        return redirect(self.get_redirect_url())
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_deletion()
        return redirect(self.get_redirect_url())

    def perform_deletion(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

templates/partials/create_update_form.html
{% csrf_token %}

<div class="w-50">
    {% for error in form.non_field_errors %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
        <div class="mb-3">
            <label class="form-label" for="{{ field.id_for_label }}">{{ field.label}}</label>
            {{ field }}
            {% for error in field.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
    {% endfor %}
</div>

<!-- <div class="w-50">
    <div class="mb-3">
        <label class="form-label" for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
        {{ form.title }}
        {% for error in form.title.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label for="{{ form.author.id_for_label }}">{{ form.author.label }}</label>
        {{ form.author }}
        {% for error in form.author.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        <label for="{{ form.body.id_for_label }}">{{ form.body.label }}</label>
        {{ form.body }}
        {% for error in form.body.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
</div> -->

<!-- <div class="mb-3">
    <label for="title" class="form-label">Title*</label>
    {% if errors.title %}
        <input type="text" name="title" class="form-control red_border" id="title" 
        placeholder="Title*" value="{{ post.title }}">
        <p class="text-danger">{{ errors.title }}</p>
    {% else %}
        <input type="text" name="title" class="form-control" id="title" placeholder="Title" value="{{ post.title }}">
    {% endif %}
</div>
<div class="mb-3">
    <label for="body" class="form-label">Body</label>
    <textarea class="form-control" name="body" id="body" rows="4">{{ post.body }}</textarea>
</div>
<div class="mb-3">
    <label for="author" class="form-label">Author*</label>
    {% if errors.author %}
        <input type="text" name="author" class="form-control red_border" id="author" 
        placeholder="Author*" value="{{ post.author }}">
        <p class="text-danger">{{ errors.author }}</p>
    {% else %}
        <input type="text" name="author" class="form-control" id="author" placeholder="Author" value="{{ post.author }}">
    {% endif %}
</div> -->

<button type="submit" class="btn btn-primary mt-3">{{ button_text }}</button>

templates/partials/navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home_page' %}">
            <img src="https://nqwebdesign.com/wp-content/uploads/2020/01/blog-icon-300x300.png" alt="" height="40">
            MyBLOG
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'home_page' %}">Home</a>
                <a class="nav-link active" aria-current="page" href="{% url 'posts:list' %}">Posts list</a>
                <a class="nav-link active" aria-current="page" href="{% url 'posts:create' %}">Add post</a>
                <a class="nav-link active" aria-current="page" href="{% url 'author_list' %}">Authors list</a>
                <a class="nav-link active" aria-current="page" href="{% url 'author_create' %}">Add author</a>
            </div>
            <div class="d-flex">
                {% if not request.user.is_authenticated %}
                <a class="btn btn-outline-success btn-sm me-3" aria-current="page" href="{% url 'login' %}?next={{ request.get_full_path }}">Login</a>
                <a class="btn btn-outline-secondary btn-sm" aria-current="page" href="{% url 'register' %}?next={{ request.get_full_path }}">Register</a>
                {% else %}
                    <div class="d-flex align-items-center me-3">
                        Hello, <a href="{% url 'user_detail' user.pk %}">{{ user.username }}</a>
                    </div>
                    <a class="btn btn-outline-danger btn-sm" aria-current="page" href="{% url 'logout' %}?next={{ request.get_full_path }}">Logout</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

templates/partials/pagination.html
<!-- <div class="pagination">
    <span class="step-links">
        <a href="?page=1">&laquo; first</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% else %}
            <span class="page-disabled">previous</span>
        {% endif %}

        <form class="current-page" method="get">
            <label for="page">
                Page <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                of {{ page_obj.paginator.num_pages }}.
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% else %}
            <span class="page-disabled">next</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    </span>
</div> -->

<nav aria-label="Page navigation">
    <ul class="pagination">
        <!-- First page -->
        <li class="page-item">
            <a href="?page=1" class="page-link">First</a>
        </li>

        <!-- Previous page -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        <!-- List of pages -->
        {% for page in page_obj.paginator.page_range %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
            </li>
        {% endfor %}

        <!-- Next page -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}

        <!-- Last page -->
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                Last
            </a>
        </li>
    </ul>
</nav>

templates/partials/post_list.html
{% if is_paginated %}
    {% include 'partials/pagination.html' %}
{% endif %}

{% for post in posts %}
    <div class="box">
        <h3><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></h3>

        <div>
            <a href="{% url 'user_detail' post.author_id %}">{{ post.author }}</a>
            {{ post.created_at|date:"d.m.Y H:i:s" }}
        </div>
        <div>Published at: {{ post.updated_at|date:"d.m.Y H:i:s" }}</div>
        
        {% if perms.posts.change_post or post.author == request.user %}
            <div><a href="{% url 'posts:update' post.pk %}">Update</a></div>
        {% endif %}
        {% if perms.posts.delete_post or post.author == request.user %}
            <div><a href="{% url 'posts:delete' post.pk %}">Delete</a></div>
        {% endif %}
    </div>
{% empty %}
    <h2 class="text-center">No posts</h2>
{% endfor %}

{% if is_paginated %}
    {% include 'partials/pagination.html' %}
{% endif %}

templates/partials/search.html
<form class="d-flex" method="GET">  
    <div class="input-group mb-3">
        <input type="search" name="search" class="form-control" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary" id="button-addon2">Search</button>
    </div>

    {% for error in form.search.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
</form>